Lanth quests
GTNewHorizons/GT-New-Horizons-Modpack pull request #10496
Opened 2022-06-15 23:59 UTC by Elisis

Update multiblock quests to reflect current behaviour

2022-06-16 00:00 UTC, Elisis commented
Wait this branch being old may fuck with the qb
Let me redo

2022-06-16 00:01 UTC, Dream-Master commented
check the nuclear changes not that we get merge issues @Elisis

2022-06-16 00:03 UTC, Elisis commented
OH
Okay I'll leave this for later then

2022-06-16 20:53 UTC, Elisis commented
It looks like it's changing a whole lot of stuff, it might not be dealing with past commits well. I may need to redo it

2022-06-17 11:55 UTC, Steelux8 requested changes

2022-06-17 11:55 UTC, Steelux8 commented on config/betterquesting/DefaultQuests.json
> +      "editMode:1": 1,
Keep edit mode off when doing quest changes.

2022-06-24 17:33 UTC, Dream-Master approved these changes

2022-06-24 17:35 UTC, Steelux8 approved these changes

2022-06-24 17:35 UTC, merged