Blacklist Gendustry Industrial Apiary from acceleration
GTNewHorizons/GT-New-Horizons-Modpack pull request #10923
Opened 2022-08-04 17:47 UTC by kuba6000

Blacklist Gendustry Industrial Apiary from acceleration to force people to use the new version
Also why there was **gregtech** apiary ? Removed it.

2022-08-04 17:49 UTC, Connor-Colenso requested changes
I would say blacklist the regular apiary as well while you are there.

2022-08-04 17:59 UTC, kuba6000 commented
> I would say blacklist the regular apiary as well while you are there.

Ok, done

2022-08-04 18:09 UTC, Connor-Colenso approved these changes

2022-08-04 18:09 UTC, merged

2022-08-04 18:20 UTC, boubou19 commented
sad day for the WA enjoyers

2022-08-05 01:08 UTC, Ethryan commented
I thought the gregtech apiary was blacklisted since you could insert upgrades that does the same thing.

If you can use a normal WA on them they get insanely broken.

2022-08-05 01:11 UTC, kuba6000 commented
> I thought the gregtech apiary was blacklisted since you could insert upgrades that does the same thing.
> 
> If you can use a normal WA on them they get insanely broken.

Not needed. All gregtech machines are blacklisted by default: https://github.com/GTNewHorizons/NewHorizonsCoreMod/blob/master/src/main/java/com/dreammaster/gthandler/accelerator/GT_MetaTileEntity_WorldAccelerator.java#L434

2022-08-09 06:31 UTC, DianeXD commented
MagicBees also has an apiary