Create TubeMadness-UYn2IASqTc2DsRiAG9stCw==.json
GTNewHorizons/GT-New-Horizons-Modpack pull request #13668
Opened 2023-06-12 02:12 UTC by Reflex18

New quest outlining how to do a basic tube network.

2023-06-12 18:36 UTC, chochem requested changes
overall I like it. more TC explanations are great :)

2023-06-12 18:36 UTC, chochem commented on config/betterquesting/DefaultQuests/Quests/NoviceThaumaturg-AAAAAAAAAAAAAAAAAAAAFg==/TubeMadness-UYn2IASqTc2DsRiAG9stCw==.json
> +      "desc:8": "So you want to move essentia from your Alchemical furance to your warded Jars without getting it all gunked up with different essentia types?\n\nWell you came to the right place, wit
'furnace'.

For the link at the end, maybe say what it is. its really not a spreadsheet, but 'A Thaumaturge's Guide to Laying Pipe
' by xlstadal. also you can remove the /edit to make it slightly shorter :P

2023-06-12 18:40 UTC, Dream-Master commented
@Reflex18

2023-06-13 01:10 UTC, chochem approved these changes
thanks!

2023-06-13 05:58 UTC, merged