Adjust igi xml to new oregen pattern
GTNewHorizons/GT-New-Horizons-Modpack pull request #13700
Opened 2023-06-14 17:02 UTC by chochem

depends on https://github.com/GTNewHorizons/InGame-Info-XML/pull/18 and thus also https://github.com/GTNewHorizons/GT5-Unofficial/pull/2081.

use the new info about the gt oregen pattern to show correctly when the player is in a ore vein chunk.

2023-06-14 19:56 UTC, wlhlm requested changes

2023-06-14 19:56 UTC, wlhlm commented on config/InGameInfo.xml
> +				<equal>
Some of your lines are indented using tabs. Please unify to spaces.

2023-06-17 18:02 UTC, Dream-Master submitted a review, later dismissed

2023-07-03 20:05 UTC, wlhlm approved these changes

2023-07-04 16:37 UTC, merged