Add quest for Drone Centre
GTNewHorizons/GT-New-Horizons-Modpack pull request #15616
Opened 2024-02-28 06:09 UTC by RealSilverMoon

2024-03-01 05:41 UTC, RealSilverMoon commented
Description and location:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/31100241/27f22650-a475-463d-a81d-57301772d696)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/31100241/308816c6-f2fe-4892-8c25-2ef2a6ef0b46)
<details>
  <summary>Description</summary>

> **Drone are not drones!**
>
> ...but they can be as industrious as bees. These new electric friends are great companions for MultiBlock machines: maintenance, control, management—they can do it all.
> 
> The Drone Center is new design machine. It doesn't need power; just put a drone into it and then it will run.
> Once running, drone will automatically scan for "Drone Downlink Module" (replacing maintenance hatches on MultiBlock machines) within a certain range and attempt to establish a connection with the host. If successfully, you can remotely control this MultiBlock machine from the Drone Centre GUI! Additionally, you can rename the machine for easier identification.
> 
> Rename can either by right-click the Drone Downlink Module or in Drone Centre GUI.
> 
> Placing more advanced drones will increase the range of central control, with no limit on the number.
> 
> Notice that drone may crash duiring operating—the probability decreases from Tier 1 to Tier 3, and Tier 3 Anti-Gravity Drones never crash. 
> Besides, If the machine host is too far from the Drone Center, the GUI remote control function will be disabled, but turn-on/off-all-button and maintenance functions will still work.
> 
> Maybe one day, our drone can control machines in other planets...drive engine online!
>

2024-03-02 19:52 UTC, chochem requested changes
I don't know anything about the drone center. Just some language criticisms:

'The Drone Center is new design machine.' -> 'The Drone Center is a newly designed machine.'

'Once running, drone will automatically scan for "Drone Downlink Module"' -> 'Once running, the drone will automatically scan for a Drone Downlink Module'

'If successfully' -> 'If successful'

'Rename can either by right-click' -> 'You can rename it either by right-clicking'

'Notice that drone may crash duiring operating' -> 'Notice that drones may crash during operation'

'but turn-on/off-all-button' -> 'but the turn-on/off-all-button'
'in other planets' -> 'on other planets'
'drive engine online!'  I dont know what that means.

2024-03-03 05:53 UTC, RealSilverMoon commented
> I don't know anything about the drone center. Just some language criticisms:
> 
> 'The Drone Center is new design machine.' -> 'The Drone Center is a newly designed machine.'
> 
> 'Once running, drone will automatically scan for "Drone Downlink Module"' -> 'Once running, the drone will automatically scan for a Drone Downlink Module'
> 
> 'If successfully' -> 'If successful'
> 
> 'Rename can either by right-click' -> 'You can rename it either by right-clicking'
> 
> 'Notice that drone may crash duiring operating' -> 'Notice that drones may crash during operation'
> 
> 'but turn-on/off-all-button' -> 'but the turn-on/off-all-button' 'in other planets' -> 'on other planets' 'drive engine online!' I dont know what that means.

Done.

2024-03-04 10:51 UTC, Dream-Master approved these changes

2024-03-04 10:51 UTC, merged