Delete servers breaking eula
GTNewHorizons/GT-New-Horizons-Modpack pull request #16821
Opened 2024-07-22 10:18 UTC by Pxx500

2024-07-22 10:27 UTC, Dream-Master requested changes
Before we are doing this I would like to contact these server owner and ask about this.

2024-07-22 12:52 UTC, Ethryan commented
While removing these, we should probably go through and take a quick look so there isn’t any more examples of this kind of monetization used in the other servers.

2024-08-23 15:38 UTC, Dream-Master approved these changes

2024-08-23 15:38 UTC, merged

2024-12-14 09:11 UTC, Einhornyordle commented
> Before we are doing this I would like to contact these server owner and ask about this.

May I ask who of us (MyFTB) you contacted?