Fix better questing bees
GTNewHorizons/GT-New-Horizons-Modpack pull request #16955
Opened 2024-08-09 16:38 UTC by vehsamrak

Fix in Bee Breeding section of better questing texts.
There seems to be a typo, because name of the bee type is "Forest".

![Снимок экрана от 2024-08-09 19-12-43](https://github.com/user-attachments/assets/77aa094a-7ee3-4c14-84d5-52ef80530f6e)

2024-08-09 20:24 UTC, chochem submitted a review, later dismissed

2024-08-09 20:25 UTC, chochem requested changes
you should only make changes in the default quests folder.

2024-08-10 03:51 UTC, vehsamrak commented
> you should only make changes in the default quests folder.

Done. Reverted fixes in `.lang` files.
Those `config/txloader/load/betterquesting/lang/template.lang` and `config/txloader/load/minecraft/lang/ru_RU.lang` would be generated from default quests json on building stage, right? @chochem

2024-08-10 13:10 UTC, chochem approved these changes
the translation file is automatic yea

2024-08-10 13:52 UTC, merged