Rework GT++ Tab to "Mass Processing"
GTNewHorizons/GT-New-Horizons-Modpack pull request #17052
Opened 2024-08-19 23:56 UTC by FourIsTheNumber

This is a minor-ish rework of the GT++ tab. Instead of being based around GT++ in particular, it is now a tab dedicated to multiblocks that scale your production (multiblocks which are stronger versions of singleblock or even multiblock machines). The vast majority of the quests in the GT++ tab fell under this category already - those which did not were simply moved to other tabs.

I have also removed some explicit references to GT++ in quest names and descriptions in order to fit the new tab.

The Mass Processing tab has several new quests:
-An introduction to multiblock processing that explains terms like "Parallel", "Overclock", "Perfect Overclock". This is right before the steam multi quests.
-An introduction to megas. I have also changed the mega quests to no longer require IV or give IV lootbags - these multis are available in HV and locking the quests this way is strange.
-Quest for the mega oil cracker, because there wasn't one.
-An introduction to HV Mass Processing multis.
-Three new quests for multis I have introduced recently.

### Affected tabs:
This is the new state of the "Mass Processing" tab. 
![2024-08-19_19 42 07](https://github.com/user-attachments/assets/080039ef-4693-4d90-a1d7-ee6aeab8ef03)

Multiblock Goals has had a few multiblocks moved in and out of it. Crucial progression multis like the QFT, Cyclotron, and Chemical Plant have been moved here. LCR, Distillation Tower, and all Megas were moved to Mass Processing.
![2024-08-19_19 42 25](https://github.com/user-attachments/assets/948f49ef-4a3c-4452-8767-f46ef2bf77f2)

How to Generate Power now has the Solar Tower. I have also moved the plasma chain here - it did not make much sense in GT++ originally and it makes less sense now. In the future I would like to move this into a dedicated fusion tab along with some other chains.
![2024-08-19_19 42 52](https://github.com/user-attachments/assets/4f5f78f6-e796-453c-bd7a-d6544d4c90ea)

Storing and Transforming Power has the Energy Buffer and Wireless Charger quests.
![2024-08-19_19 43 08](https://github.com/user-attachments/assets/2d90d974-da34-49a9-ba78-8817c3b50e6f)

### New Quests:

![2024-08-19_19 50 27](https://github.com/user-attachments/assets/c93518f4-3d8a-48c9-b442-822b2792eab1)
![2024-08-19_19 50 46](https://github.com/user-attachments/assets/f41eba60-9c0d-438f-928e-d15972fd24ab)
![2024-08-19_19 50 58](https://github.com/user-attachments/assets/9e8829da-c382-41ad-b93e-b8d00ef4a07d)
![2024-08-19_19 51 12](https://github.com/user-attachments/assets/2dac67d9-3ab7-473e-b580-438008801114)
![2024-08-19_19 51 33](https://github.com/user-attachments/assets/dcdf28d2-3ecd-431a-955f-2be9621ee91e)
![2024-08-19_19 51 49](https://github.com/user-attachments/assets/67219784-b324-4c4c-86c6-6e26699da332)
![2024-08-19_19 52 01](https://github.com/user-attachments/assets/6fe1b85b-aac8-452f-88c0-3890adf281fc)

One quest was removed: The quest for GT++ books. I have moved these to be optional tasks within their respective multis instead.

2024-08-20 07:31 UTC, Baerschen commented
Just downloaded your branch and looked into it ingame and i must say this looks pretty good. At first I thought it would look cluttered as i mentioned on discord but thats actually not the case. This makes it way better for adding new multis aswell down the line. Very well done! On top of that explaining mechanics like parallel and perfect OC is very well done and much needed information for new players.

2024-08-20 08:48 UTC, chochem requested changes
heavily dependent on https://github.com/GTNewHorizons/GT5-Unofficial/pull/2799
as long as that is the case you will need to wait until that is fully resolved

2024-08-20 09:07 UTC, chochem commented
also something else: 
the start of the tab is very broken right now. "multiblocks in steam age? impossible" was forgotten. while multiblock revolution doesnt have a prereq. those should probably be one and the same quest on the old id and in both tabs.

2024-08-20 10:06 UTC, Dream-Master commented
> heavily dependent on [GTNewHorizons/GT5-Unofficial#2799](https://github.com/GTNewHorizons/GT5-Unofficial/pull/2799) as long as that is the case you will need to wait until that is fully resolved

this pr is done and can be reviewed

2024-08-20 10:08 UTC, Baerschen commented
> also something else: the start of the tab is very broken right now. "multiblocks in steam age? impossible" was forgotten. while multiblock revolution doesnt have a prereq. those should probably be one and the same quest on the old id and in both tabs.

Yeah the quest in LV tab tells you to look at the GT++ Tab so that needs to be adjusted. Would also add the information that multis void on power loss to the revolution quest and remove it from the central steam quest and potentially other central quests.

2024-08-20 16:50 UTC, chochem commented on config/betterquesting/DefaultQuests/Quests/HowtoGeneratePow-AAAAAAAAAAAAAAAAAAAACQ==/DeepEarthHeating-AAAAAAAAAAAAAAAAAAAKzg==.json
> +          "id:8": "gregtech:gt.blockframes",
here is another

2024-08-20 16:50 UTC, chochem commented on config/betterquesting/DefaultQuests/Quests/MultiblockGoals-AAAAAAAAAAAAAAAAAAAADA==/DiggingDeepforWa-jreOZVXRQa2sGXViV7-3Gg==.json
> +          "id:8": "gregtech:gt.blockframes",
and here

2024-08-20 17:15 UTC, FourIsTheNumber commented
> > also something else: the start of the tab is very broken right now. "multiblocks in steam age? impossible" was forgotten. while multiblock revolution doesnt have a prereq. those should probably be one and the same quest on the old id and in both tabs.
> 
> Yeah the quest in LV tab tells you to look at the GT++ Tab so that needs to be adjusted. Would also add the information that multis void on power loss to the revolution quest and remove it from the central steam quest and potentially other central quests.

Merged these two quests, updated the text, and shared them between the tabs. Moved power loss info as well

2024-08-27 07:36 UTC, Dream-Master approved these changes

2024-08-27 07:36 UTC, merged