Novice Thaumaturgy Questbook Changes
GTNewHorizons/GT-New-Horizons-Modpack pull request #17331
Opened 2024-09-14 01:23 UTC by PlayfulPiano

- Increased "Your First Wand" icon size
- Modified required progression path to allow quest access for both "Not For Soup" (Crucible) & "A Table to Work On" (Arcane Worktable) without needing "Seen the Unseen" (Thaumometer) & "Getting Shards" (Infused Shards), as both are not required material wise.
- Added a new intermediary quest that uses the old "Getting Shards" description in relation to infused stones ("Processing Infused Stones")
- Added a new quest for interacting with a Pech ("A Pechuliar Merchant"), can be used to unlock "Getting Shards"
- Added a new secret quest (and quest trigger) for obtaining a Profane Wand ("A Dangerous Trade"), unlocking the questpage early if discovered.
- Added "Getting Shards" to both "Crystal Clusters" and "Balanced Shards sdrahS decnalaB" due to the new progression changes.

![image](https://github.com/user-attachments/assets/d8dae130-e2bb-42e8-9bf7-22615568e1e8)
![image](https://github.com/user-attachments/assets/24ca3421-f4b5-4c82-91a1-2c7a3ebb8987)
![image](https://github.com/user-attachments/assets/861fcbef-ecbd-42f2-9b7a-81a8552ecd7b)
![image](https://github.com/user-attachments/assets/655a3dd8-e132-4c9b-a0ff-424d1d66a356)
![image](https://github.com/user-attachments/assets/b843f651-c049-4028-a1d7-28338da6aa22)
![image](https://github.com/user-attachments/assets/38d7e2f2-a500-4805-a044-c5572b2d8c4a)
Showcasing the secret profane wand quest:
![image](https://github.com/user-attachments/assets/0830a68e-ab0d-412e-8dd6-b80e29c8fee1)
![image](https://github.com/user-attachments/assets/d3f6986d-1124-4be5-9788-f172f9a5523a)

2024-09-14 01:36 UTC, FourIsTheNumber commented on config/betterquesting/DefaultQuests/Quests/NoQuestLine/TriggerPlatlineO-AAAAAAAAAAAAAAAAAAALXA==.json
This deletion looks unintended

2024-09-14 01:39 UTC, PlayfulPiano commented on config/betterquesting/DefaultQuests/Quests/NoQuestLine/TriggerPlatlineO-AAAAAAAAAAAAAAAAAAALXA==.json
huh, you're correct. I didn't even touch this quest, weird. What would be the best way to fix this, on the PR side of things?

2024-09-14 01:42 UTC, FourIsTheNumber commented on config/betterquesting/DefaultQuests/Quests/NoQuestLine/TriggerPlatlineO-AAAAAAAAAAAAAAAAAAALXA==.json
> huh, you're correct. I didn't even touch this quest, weird. What would be the best way to fix this, on the PR side of things?

Go to a fresh copy of the bq configs, go to that file path, copy the deleted quest back into your repo and then commit/push again

2024-09-14 01:46 UTC, PlayfulPiano commented on config/betterquesting/DefaultQuests/Quests/NoQuestLine/TriggerPlatlineO-AAAAAAAAAAAAAAAAAAALXA==.json
done

2024-09-14 10:33 UTC, chochem requested changes
- Dont change the start. these are critical main quests. The requirements are intentional.
- Dont make a secret quest. People already hate the ones we have as they dont know how to finish the respective quest tab. Either this deserves a proper quest or not. Probably best to just use the trigger without that one.
- That processing infused stones quest looks totally useless. whats the point?
- Pech looks good. but we dont use meeting tasks anywhere else. have you tested that it works well?

2024-09-14 12:30 UTC, Dream-Master commented
meeting quests are a nice idea if they working. never tested it.

2024-09-14 13:14 UTC, PlayfulPiano commented
I'll have to test back when I get home from work today (assumed they already had precedent in the quest book, didn't realize this wasn't the case).

As for early progression changes, would it be better if the thaumometer quest was a checkbox/optional retrieval task combination? Main thing is so players who get an early wand before laser engraver can still progress in the quest book based on what they actually have access to (so workbench and crucible, where neither needs the thaumometer or shards).

As for the processing infused stones quest, that's meant to be an intermediate quest to store the old getting shards description for the typical LV progression path, while also allowing pechs to act as an alt progression path for pre LV shards.

2024-09-14 13:16 UTC, PlayfulPiano commented
Also when I get back home might look into adding some more information about the strength/advantages of early thaumcraft progression (redstone, lapis, sugar sources) and possibly a hint to the profane wand somewhere in the stone age quest page.

The profane wand secret aspect, yeah I can instead make it just the trigger if it's that problematic.

2024-09-14 23:51 UTC, PlayfulPiano commented
Back home, and I made the adjustments requested.

- Removed the "A Dangerous Trade" secret quest
- Added "50 vis" quest completion reward to the "Profane Wand" trigger quest
- Readded the Thaumometer prerequisite to Scribing Tools
- Added "Early Scribing Tool" trigger quest, requires "Profane Wand" trigger quest as a prerequisite
- Removed the "Infused Stone Processing" quest, moved info into the normal Infused Stone quest
- Removed the "Getting Shard" prereq requirements for balanced shards & crystal cluster quests
- Some quest repositioning
- Some quest description changes

2024-09-15 00:26 UTC, Alastors commented
I disagree with chochom on the secret quest stuff

2024-09-15 00:27 UTC, Alastors commented
Honestly, overall from face value these seem like good changes, wandskip and all

2024-09-15 00:36 UTC, PlayfulPiano commented
> I disagree with chochom on the secret quest stuff

/shrug

I can revert it back to include the secret quest but yeah uh we should have an agreement on that lol

2024-09-15 00:57 UTC, chochem requested changes
much better now, one big thing left though.

the warp warnings really need to back in main progression and main quest. its just that important.

2024-09-15 02:39 UTC, PlayfulPiano commented
Alright, PR updated hopefully for the last time now.

- Added back warp warnings to the main quest prereq path
- Separated the "Useful Plant Life" quest into multiple quests with more detailed information
- Swapped "Primal Shrooms" and "Enchanted Earth" for the plant quest related prereq
- Some quest position changes
- Added mention about the new 2.7 warp sounds

2024-09-15 10:42 UTC, chochem approved these changes
awesome, thanks for the patient follow-ups!

2024-09-15 11:07 UTC, merged