WG transmutation "fix"
GTNewHorizons/GT-New-Horizons-Modpack pull request #6686
Opened 2020-09-24 19:57 UTC by 0lafe

Should be a "fix" for OP transmutations from WG, until it's either balanced or removed differently

2020-09-24 20:00 UTC, bartimaeusnek requested changes
no.

2020-09-24 20:03 UTC, 0lafe commented
Still haven't seen that entire rework of essentia gen, maybe then we can allow these transmutations lol

2020-09-24 20:04 UTC, bartimaeusnek commented
> 
> 
> Still haven't seen that entire rework of essentia gen, maybe then we can allow these transmutations lol

Go ahead, that would be the correct fix. do it instead of destructively turning off features you dont like.

2020-09-24 20:04 UTC, closed without merging

2020-09-24 20:06 UTC, 0lafe commented
I don't think that method is reasonable or achievable. I'm referring to what you always brought up as a counter point to how dumbly OP much of this is. I'm not really sure how you can see most of these transmutations being OK

2020-09-24 20:18 UTC, mitchej123 commented
It should be balanced, not removed.

2020-09-24 20:21 UTC, 0lafe commented
I agree, but the balance is difficult for this, and would need a LOT of stuff changed. I don't think leaving it in an OP state is better than removing it though. If lots of thaum got changed I could see it coming back in a balanced state, but I don't think those changes would ever happen

2020-09-24 20:33 UTC, mitchej123 commented
I'm fine with having alternatives to tech, gogo magic!

2020-09-25 02:49 UTC, Rakdarian commented
Leave the magic alone unless you want to take the initiative and rebuild it from the ground up.