Change AE2 storage component recipes
GTNewHorizons/GT-New-Horizons-Modpack pull request #7847
Opened 2021-04-22 17:59 UTC by Prometheus0000

Makes them not recursive. See #7839.

2021-04-22 18:08 UTC, Dream-Master commented
They ass cheap now. Replace a component with a plate ?

2021-04-22 18:09 UTC, Glease commented
@Dream-Master they need to be cheaper than drawers. they are more tps friendly and is more pleasing to look at than a huge solid drawer cube. 

currently the only reason to use drawers at that scale is because the alternative is too expensive.

2021-04-22 18:10 UTC, Dream-Master commented
And if you change it please add a control circuit to the recipe

2021-04-22 18:10 UTC, Prometheus0000 commented
See the discussion on the issue and in #github-discussion. And the previous discussion and PR.

2021-04-22 18:10 UTC, Prometheus0000 commented
I knew I forgot something.

2021-04-22 18:12 UTC, Dream-Master commented
yeah but plates phew? Maybe we can think of a better recipe component for a storage then a plate ?

2021-04-22 18:14 UTC, Prometheus0000 commented
Wouldn't the data be stored on the processor+chips? With the plates keeping it together and the crystal as some kind of medium?

2021-04-22 18:14 UTC, Dream-Master commented
compared to the old recipe we set recipe from 100% Material cost to 1%

2021-04-22 18:15 UTC, Prometheus0000 commented
Is that bad? People weren't using them before.

2021-04-22 18:15 UTC, Dream-Master commented
Even vanilla recipe more expensive
https://ftbwiki.org/4k_ME_Storage_Component

2021-04-22 18:16 UTC, GTNH-Afx237v7 commented
"Set recipe costs from 100% to 1%" ->Yes because the old recipe was insane. Compared to super/quantum chests the AE components were just ridicuoulusly expensive; and with the non-ticking TE handler that repolainen implemented, the AE disks became even less attractive

2021-04-22 18:17 UTC, Prometheus0000 commented
It's still more expensive, as we have the intermediary item processor item. And the whole idea is to get away from recursive crafting.

2021-04-22 18:19 UTC, Prometheus0000 commented
We also have the very expensive circuits in ours, whereas vanilla does not.

2021-04-22 18:19 UTC, GTNH-Afx237v7 commented
then i suggest we take the discussion back to the RFC thread; I'll post what botn365 mentioned in the discord so we have a different perspective as well

2021-04-22 18:23 UTC, Prometheus0000 commented
Why though? Just make the current tier chip more expensive?

2021-04-22 18:23 UTC, Prometheus0000 commented
Also, what do you mean by 'chip', there's 3 different things it could be?

2021-04-22 18:26 UTC, Dream-Master commented
Why more expensive? if you se only one instead of 4 from previous tier? Or we can change the recipes of the ae ships. this recipes are very old and outdated too.

2021-04-22 18:37 UTC, Prometheus0000 commented
What? You're the one that wanted to make the recipes more expensive? I'm saying make the item processor more expensive instead of using the previous tier of item processor. Which I already said on discord. Did you read the discussion?

2021-04-22 18:39 UTC, Dream-Master commented
You made the recipe very much more cheaper and i want to take care make the recipe more balanced. With the changes i will probably doing we not 99% cheaper but maybe 80%.

2021-04-22 18:44 UTC, Prometheus0000 commented
And I'm asking why you want to add 
![image](https://user-images.githubusercontent.com/8517039/115768791-c4e9ed00-a378-11eb-83ba-530a792955a9.png)
A previous tier of these in, when you can simply change their recipe?
![image](https://user-images.githubusercontent.com/8517039/115768922-f2369b00-a378-11eb-8799-d0fac277f133.png)
Like add in some circuits or something.

Personally, I till think they're expensive enough, but I dunno.

2021-04-22 18:50 UTC, Dream-Master commented
This recipe is very old. We could add a solder and a control circuit. Or /and add some fine wire or some things make the recipe looks a bit nicer.I dont speak about changes you did to components i speak about minimal changes and adjustments :)

2021-04-22 19:16 UTC, Dream-Master requested changes

2021-04-22 19:16 UTC, Dream-Master commented on scripts/Extra-Cells.zs
1920 was ok

2021-05-04 19:28 UTC, Prometheus0000 commented
Forgot to update, they now look like https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7839#issuecomment-826104395

2021-05-04 19:43 UTC, Dream-Master commented
lets use a 3:1 ratio not ix it up. And yes plates are to cheap

2021-12-08 19:15 UTC, closed without merging