Remove MT Platinum recipe
GTNewHorizons/GT-New-Horizons-Modpack pull request #8573
Opened 2021-09-21 09:13 UTC by Elisis

This recipe fully bypasses any need of using the "plat" line of platline far earlier than would be appropriate.
(You're welcome, Colen)

2021-09-21 09:16 UTC, GTNH-Colen commented
This recipe is balanced, it's expensive early game and worth it later in the game. It's way less energy efficient but allows users to get a lot of platinum when they start to need it, I believe it was discussed before to nerf it but I see no point really. You still have to do the plat line because of the all the other parts, so there is no tier skipping.

2021-09-21 09:17 UTC, GTNH-Colen reviewed
no

2021-09-21 09:24 UTC, GTNH-Afx237v7 commented
Please no. If this is considered bypassing I suggest to increase eu needed to make the platline more attractive. But straight up deleting - „That’s a negative, Rafterman.“

2021-09-21 09:25 UTC, Prometheus0000 commented
I have no strong opinions one way or the other about this matter. Doing this doesn't get you the rest of the platline metals, but does seem a little easy.

2021-09-21 09:25 UTC, Elisis commented
Increasing by a factor of 10-100 would also be reasonable, yeah

2021-09-21 09:31 UTC, Dream-Master commented
It bypassing indeed the whole process. If platinum process unbalanced we better do changes there also

2021-09-21 09:33 UTC, boubou19 commented
Right now, it's 2 minutes and 2 seconds to get a gold dust turned into a platinum dust. At EV, it's 8 minutes and 8 seconds. That's still less efficient than converting platinum metallic powder to platinum nugget early game, no need for it to get it nerfed. After that, if you use the MT recipe to bypass the platinum making out of the plat line setup, then what you are doing is simply preventing yourself from getting all the other ores from the line, which are needed to progress. So the recipe is just here to make a quick batch of it when you need it, not here to be exploited continuously. I Say this is really not needed to touch it at all.

2021-09-21 09:42 UTC, Sphyix commented
Do not delete or nerf this recipe.
The amount of platinum needed endgame is just ridicoulus and that's the only way of getting it at a decent speed without spamming so many LCRs (and don't forget the output in tiny dusts for the platline)
One-ticking a platline is totally not enough to get the amount of platinum needed.
What we actually need is an alternative for the rest of the materials aswell to avoid spamming one-tick machines endgame and focus the amount of lag made and the attention on some other lines.

Do you know that for 1 (1!) UV Ultimate Battery (you need 8 for a capacitor for LSC) you need 180k platinum?
This is 1.4 million platinum for 1 Ultimate Capacitor
That is 12.6 million tiny dusts, 6.3 million ticks, 87 hours to get the amount of platinum needed with a 1 tick platline
That's just an example, platinum is needed everywhere and the amount made with single LCRs platline is never enough at endgame.

You know what happens when something takes too much time? More of the same lines are spammed.

Remaking the same line twice cause it can't output enough of what you need is not fun nor an interesting mechanic, 
so there should be an alternative for endgame platline skipping, what needs to be done is adding the rest of the materials to the MT recipes, not remove platinum.

2021-09-21 09:46 UTC, Pxx500 commented
> so there should be an alternative for endgame platline skipping
The amount of platinum needed should be reduced and changed for something more "high tier"

2021-09-21 09:50 UTC, boubou19 commented
> The amount of platinum needed should be reduced and changed for something more "high tier"

Agreed, but, that requires a total overhaul of the crafting components and is far beyond the scope of this ticket.

>Also platline could get 9x recipes with x9 time so tiny piles are avoided because It's very inefficient at high tiers

Concerning the x9 boost that would be welcomed at later tiers, but i don't think it's necessary for when you first make your plat line.

2021-09-21 09:51 UTC, Sphyix commented
> > so there should be an alternative for endgame platline skipping
> 
> The amount of platinum needed should be reduced and changed for something more "high tier"
> Also platline could get 9x recipes with x9 time so tiny piles are avoided because It's very inefficient at high tiers

LuV and ZPM stuff keeps getting used in high tier recipe, making UHV or UEV circuits requires LuV and ZPM parts, that needs platline stuff
I'd be fine if with the removal of the MT recipe, a platline 9x recipe is added to be able to avoid spamming more machines
I still think platline doesn't belong to UHV-UEV tiers, cause you have other stuff to make in your base, but that's just my opinion

2021-09-21 09:53 UTC, Pxx500 commented
> Concerning the x9 boost that would be welcomed at later tiers, but i don't think it's necessary for when you first make your plat line.

As long as processing time is also multiplied it won't change early tiers balance wise and changes are minimal to implement, much less spamming lategame
There is no need to add a new x9 recipe since editing the existing one won't cause problems eary game

2021-09-21 09:57 UTC, Sphyix commented
> Increasing by a factor of 10-100 would also be reasonable, yeah

Have you ever played endgame? Do you know how much plat is needed?
Let's take into consideration the Ultimate Capacitor (UHV)
1.4 million platinum with a setup like mine (32 infinity large plasma turbines making 120 mil eu/t) while using the WHOLE power used only for platinum, is gonna take 32 hours to make the platinum needed if the MT power cost is changed to a 10x, and 320 hours if it's at 100x
My setup is overkill, boubs's setup would take 128 hours of power to make the same amount of platinum needed with the MT power cost at 10x as he uses a more normal setup with 9 large plasma turbines 
So making the cost 10x would have the same effect as to remove the recipe

2021-09-21 09:58 UTC, Dream-Master commented
> Do not delete or nerf this recipe.
> The amount of platinum needed endgame is just ridicoulus and that's the only way of getting it at a decent speed without spamming so many LCRs (and don't forget the output in tiny dusts for the platline)

If you dont use the platinum line and use this instead then something is wrong. So the Platinum line need a rework and this recipe as well. Skipping is no way to play GTNH.

> One-ticking a platline is totally not enough to get the amount of platinum needed.
> What we actually need is an alternative for the rest of the materials aswell to avoid spamming one-tick machines endgame and focus the amount of lag made and the attention on some other lines.
> 
> Do you know that for 1 (1!) UV Ultimate Battery (you need 8 for a capacitor for LSC) you need 180k platinum?
> This is 1.4 million platinum for 1 Ultimate Capacitor
> That is 12.6 million tiny dusts, 6.3 million ticks, 87 hours to get the amount of platinum needed with a 1 tick platline
> That's just an example, platinum is needed everywhere and the amount made with single LCRs platline is never enough at endgame.
> 
> You know what happens when something takes too much time? More of the same lines are spammed.
> 
> Remaking the same line twice cause it can't output enough of what you need is not fun nor an interesting mechanic,
> so there should be an alternative for endgame platline skipping, what needs to be done is adding the rest of the materials to the MT recipes, not remove platinum.

2021-09-21 10:07 UTC, iouter commented
all late game recipes need to be reconsidered. for example, it is best to avoid using too many low level materials. but before making such a plan, keep the recipe.

2021-09-21 10:12 UTC, Dream-Master commented
> all late game recipes need to be reconsidered. for example, it is best to avoid using too many low level materials. but before making such a plan, keep the recipe.

sure if we move/change the recipe we do the other stuff around also

2021-09-21 10:19 UTC, Dream-Master commented
Or we remove the device and add a multiblock for that process with more input slots and a % loss depends on the tier.

2021-09-21 10:22 UTC, Pxx500 commented
> Or we remove the device and add a multiblock for that process with more input slots and a % loss depends on the tier.

Why not just scale platline recipes x9? Full dusts instead of tiny piles

2021-09-21 10:29 UTC, Dream-Master commented
> > Or we remove the device and add a multiblock for that process with more input slots and a % loss depends on the tier.
> 
> Why not just scale platline recipes x9? Full dusts instead of tiny piles
> Also why the loss? For mass production?

As i said erlier the whole process need to be redone /changed/buffed/nerfed etc

2021-09-21 10:37 UTC, iouter commented
> Or we remove the device and add a multiblock for that process with more input slots and a % loss depends on the tier.

that makes no more sense. the best way is to design a powerful material to replace a large amount of platinum. In this way, we need to reconsider the tech tree of luv +, what materials they use, what kind of multiblock they will make, what kind of circuit they will have, what kind of chemical chain they will have and so on, so as to adapt to a GT with more voltage.

2021-09-21 10:41 UTC, Pxx500 commented
> > Or we remove the device and add a multiblock for that process with more input slots and a % loss depends on the tier.
> 
> that makes no more sense. the best way is to design a powerful material to replace a large amount of platinum. In this way, we need to reconsider the tech tree of luv +, what materials they use, what kind of multiblock they will make, what kind of circuit they will have, what kind of chemical chain they will have and so on, so as to adapt to a GT with more voltage.

We have a lot of powerful materials, the problem is recursive crafting which uses low tier components that require platinum

2021-09-21 11:56 UTC, Alexdoru commented
> One-ticking a platline is totally not enough 
> This is 1.4 million platinum for 1 Ultimate Capacitor
> That is 12.6 million tiny dusts, 6.3 million ticks, 87 hours to get the amount of platinum needed with a 1 tick platline

You are fake news, 1.4 million platinum at a rate of one per tick is less than 20 hours and not 87 hours. 

If you can’t use a calculator maybe don’t play gregetch ?

And this is actually what my platline is producing. I am in the endgame and I turned off my platline a long time ago because it was producing too much. The MT recipe and the whole platline is fine. 
If you don’t want to waste all of your energy in MT maybe make a platline ??
If you want to play the endgame you can’t expect your infrastructure from 5 tiers ago to be sufficient for the needs of the latests crafts in the game.

2021-09-21 12:03 UTC, boubou19 commented
I think it depends if you go PAs or not for the duration.

2021-09-21 13:22 UTC, Sphyix commented
> > One-ticking a platline is totally not enough
> > This is 1.4 million platinum for 1 Ultimate Capacitor
> > That is 12.6 million tiny dusts, 6.3 million ticks, 87 hours to get the amount of platinum needed with a 1 tick platline
> 
> You are fake news, 1.4 million platinum at a rate of one per tick is less than 20 hours and not 87 hours.
> If you can’t use a calculator maybe don’t play gregetch ?


I know how to use a calculator, you should check recipes a bit better and be a bit more respectful towards other players even if they could be or are wrong.

A 1 ticking LCR making tiny reprecipitated platinum dust makes 2 tiny dusts per tick, you need 18 tiny dusts to get 2 full platinum dusts as per recipe
1.4 million full dusts * 9 = 12.6 million tiny dusts / 2 (getting 2 tiny per tick) = 6.3 million ticks

2021-09-21 14:19 UTC, Alexdoru commented
> The amount of platinum needed endgame is just ridicoulus and that's the only way of getting it at a decent speed without spamming so many LCRs (and don't forget the output in tiny dusts for the platline)


It is so ridiculous that with less than 3m eu/t and one multi per recipe (and 5 LCR) you can make 20 platinum per second. 


> 1.4 million platinum with a setup like mine (32 infinity large plasma turbines making 120 mil eu/t) while using the WHOLE power used only for platinum, is gonna take 32 hours to make the platinum needed if the MT power cost is changed to a 10x, and 320 hours if it's at 100x


but keep voiding your power in MT I guess

2021-09-23 10:51 UTC, Dream-Master commented
@Elisis change it to x10 use the power and i let it in

2021-09-23 10:55 UTC, Dream-Master approved these changes

2021-09-23 11:02 UTC, Dream-Master commented
*https://github.com/GTNewHorizons/bartworks/pull/39

2021-09-23 11:04 UTC, Dream-Master commented
@GTNH-Colen @GTNH-Afx237v7 @Alexdoru @Sphyix @iouter @Pxx500 @boubou19 @Prometheus0000

2021-09-23 11:13 UTC, Prometheus0000 commented
😐

2021-09-23 11:25 UTC, GTNH-Afx237v7 commented
No more tiny dusts: check
Increased voltage requirements: check
Decrease processing time: check
Change ability to 1 tick from LuV to ZPM: check
Save tps for everyone: check

OK for me!

2021-09-23 11:31 UTC, Sphyix commented
You can just remove the recipe instead of making it 10x power, it's pretty much the same thing

2021-09-23 11:51 UTC, boubou19 commented
Right now, the MT is useful for sunnarium, and for platinum, rest is kinda useless. x10 the gold to platinum recipe will just make it useless, so at that point, i think it's better to remove it. This issue just scratched the surface of a way bigger issue that is the platinum need at endgame.

2021-09-23 12:31 UTC, Dream-Master commented
@Elisis ok so remove it .

2021-09-24 00:10 UTC, Prometheus0000 commented
So, uh, what is the massive platinum use in the endgame, anyways?

2021-09-24 04:20 UTC, boubou19 commented
from my observations, it usually comes from the circuits in the crafts

2021-09-24 05:21 UTC, Prometheus0000 commented
OK, which circuits though? All of them? Specific ones? Wetware series? Bio series? Nano? Quantum?

2021-09-24 06:14 UTC, GlodBlock commented
this recipe contributes to most platium consumption of ciruits.
![图片](https://user-images.githubusercontent.com/60341015/134626538-6dc46290-64d3-49d4-ba31-a83bb8961bc8.png)

the second is the quantum-series ciruits before asoc is avaible.
![图片](https://user-images.githubusercontent.com/60341015/134626984-d7550a0a-3f3c-4073-ae53-a3a013593556.png)

2021-09-24 09:06 UTC, Pxx500 commented
Right now I think the worst part about the platinum usage is how much low tier recursive crafting is involved, to make biowares you have to use parts from IV.
How about adding new PBI board that could used as a base for more advanced boards such as wetware lifesupport board and bio mutated board? It could be made cheaper by using multiple different resources and It would increase the tier of the boards from epoxid based to PBI based. Platinum could still be used

2021-09-24 09:14 UTC, Prometheus0000 commented
A new board to avoid recursive crafting sounds good (recursive always bad 😠 ), maybe make a ticket with the suggestions there? I'm not sure which boards should change though, I think there was like 3-5 in the chain?

2021-09-24 09:47 UTC, Alexdoru commented
Unpopular opinion : the platinum usage in endgame is fine, don’t change the crafts. And platinum production has been made easier with the full dust recipe addition

2021-09-24 10:22 UTC, boubou19 commented
> Unpopular opinion : the platinum usage in endgame is fine as is, don’t change the crafts. And platinum production has been made easier with the full dust recipe addition

Recursive crafts are bad, at endgame when you start spamming stuff, you trigger a lot of craft simultaneously, for stuff that shouldn't be used at those tiers. so you consume some ticktime for something that could totally be avoided by changing a few recipes. While it's totally fine for single player, it's unecessary lag for endgame players on a server. Using recursive recipes adds nothing but time gates, which aren't really anymore given you are 3-4 tiers above the items' tier spammed. I don't see why it is bad to change the material sink a bit?

2021-09-24 10:26 UTC, Pxx500 commented
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8596

2021-09-24 13:41 UTC, GTNH-Colen commented
Bruh what the fuck happened here, this is ridiculous. Literally everyone simping for this change has not played endgame and has no idea what they're on about.

2021-09-24 13:59 UTC, Pxx500 commented
> Bruh what the fuck happened here, this is ridiculous. Literally everyone simping for this change has not played endgame and has no idea what they're on about.

What is endgame to you? Stargate tier?

2021-09-24 16:47 UTC, GTNH-Colen commented
> What is endgame to you? Stargate tier?

The stargate is just the beginning 😎

2021-09-25 00:56 UTC, GTNH-Colen requested changes
no

2021-09-25 00:57 UTC, GTNH-Colen commented
I'm open to a reasonable nerf but anyone suggesting 10x can jog on. Perhaps 60m EU per Pt.

2021-09-25 01:24 UTC, Sphyix commented
Considering the changes to the plat line this recipe can just be removed.
Any nerf to it makes it completely useless anyway

2021-09-25 07:03 UTC, Pxx500 commented
I'd say it can be left as is or nerfed, we don't need to remove all recipes just because they are suboptimal. We can leave possibility of making materials different methods to encourage searching for off-meta solutions. The platline path is getting enough advertising so if people don't want suboptimal solutions they won't use this

2021-10-04 13:11 UTC, Prometheus0000 commented
So what's happening here? Are we removing it, not removing it, making it more expensive, or something else?

2021-10-04 13:37 UTC, Dream-Master commented
Depends. Maybe we need to check platinum line first and judge later about to remove recipe or make it more expensive.

2021-10-04 22:50 UTC, Alexdoru commented
According to my sheet it costs around 470 000eu to craft a platinum dust via the platline.
https://docs.google.com/spreadsheets/d/1zcxyhI1AcR90d1mpmI77elxmXtcGXtgS0G-H5KCiIo0/edit?usp=sharing

2021-11-14 06:46 UTC, Dream-Master commented
We not done here and this recipe get removed or will be more expensive. I don't forget it 😎

2021-11-14 06:51 UTC, Sphyix commented
> We not done here and this recipe get removed or will be more expensive. I don't forget it 😎

We should see how the new change behaves in-game on high tier players before removing the currently only way to make fast platinum
So since this has been here for a lot of time, what about thinking of removing it next patch and leaving it in for now?

2021-11-14 08:25 UTC, Dream-Master commented
look what is happend with pollution....  No we doing it now/next stable update.

2021-11-14 08:40 UTC, Sphyix commented
> look what is happend with pollution.... No we doing it now/next stable update.

This isn't a big issue like pollution.
Pollution needs a lot of time for the rework, it's something completely different from an issue like this.
This is just a matter of hearing feedback and deciding to remove a line of code or not, but you can't have feedback until the change is released

2021-11-14 12:04 UTC, GTNH-Colen commented
When you can't close a two month old, stale, unpopular ticket you know something has gone wrong 🙄

2021-11-15 00:25 UTC, Elisis commented
> When you can't close a two month old, stale, unpopular ticket you know something has gone wrong 🙄

Shhh, it's okay Colen. I won't let the scary old PR hurt you.

2021-11-17 00:25 UTC, boubou19 approved these changes

2021-11-17 14:04 UTC, GTNH-Colen approved these changes

2021-11-17 17:06 UTC, merged