Sanity Adjusting Some Recipes
GTNewHorizons/GT-New-Horizons-Modpack pull request #9373
Opened 2022-01-06 03:03 UTC by ScriptedPiky

Adjusts the following:
Sanctus: Gold > Rose Gold
Incedium: Lava Bucket > Ignis Crystal Dust, Firestone Dust > Small Firestone
Virtus: Plutonium 239 > Fiery Steel Dust

Makes cutting the Slate variants not take a million years for the sake of it taking forever

2022-01-06 22:03 UTC, GTNH-Colen approved these changes

2022-01-06 23:06 UTC, Dream-Master commented
before we merge this i think we have to open an rfc issue to discuss wich changes are good/balanced etc

2022-01-06 23:07 UTC, Dream-Master requested changes
before we merge this i think we have to open an rfc issue to discuss wich changes are good/balanced etc

2022-01-06 23:08 UTC, GTNH-Colen commented
Didn't we have a RFC surrounding this? Or at least extensive chats on the discord, most people agreed that BM is stupidly grindy early game for no reason. I've done all of BM to get the infinity armour and resorting to using an autoclicker is just dumb.

2022-01-06 23:09 UTC, Dream-Master commented
i am not in general about a change but change a few numbers not balancing it.

2022-01-06 23:38 UTC, ScriptedPiky commented
Based on all the comments and history I know of from BM and how people generally reacted, most of these changes are aimed reducing early game grind, adjusting Incedium to be way less cancer to craft, makes Virtus not require Pu-239 when this BM "Core" is required in around HV-ish tier, and makes the slate cutting not a forever process (the most basic was 90 seconds at MV), something that many disliked

This is smallish and aims to fix the more broad & easily adjustable values. Other problems I am uncertain how to go about, except the meteors.

2022-01-06 23:50 UTC, GTNH-Colen commented
Agreed, this is broadly a good start given slates are used in nearly all blood magic items. This helps hugely in the early game. The only other thing I can think of that should be adjusted off the top of my head is blood iron.

2022-01-07 00:03 UTC, ScriptedPiky commented
Ah yeah that's also another fun one with huge LP costs. I'll try looking into it at some point to find an "okay" value that isn't over "buffing" it by accident.

2022-01-08 11:14 UTC, Dream-Master commented
@ScriptedPiky let me know when it is done

2022-01-15 11:08 UTC, Dream-Master approved these changes

2022-01-15 11:08 UTC, merged